### ISSUE TITLE
incidents-dataset

### ISSUE THREAD

**Issue by yrcrcy** [ethanweber/IncidentsDataset#1]
Thank you for your contribution to this data set. I want to download this dataset for academic research, not for commercial use. I hope you can provide this data set, thank you.

**Comment by ethanweber** [comment]
Hello @yrcrcy, thanks for your interest in the dataset! Can you email `incidentsdataset@googlegroups.com` to make a request? More details can be found at https://github.com/ethanweber/IncidentsDataset#obtain-the-data.

**Comment by luoolu** [comment]
I've submitted an application but haven't heard back
@ethanweber，
my gmail,argluolu@gmail.com
